[mypy]
strict = true
python_version = 3.12
mypy_path = $MYPY_CONFIG_FILE_DIR/ame/python/src

[mypy-test_package,test_perf_smoke,check_commit_msg_test,check_packages_test,ruff_bin_test,types_runner_test]
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
