load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//tools/bazel:defs.bzl", "starlark_checks")
load("//tools/python:defs.bzl", "ame_test", "python_checks")

exports_files([
    "check_runner.py",
    "pytest_runner.py",
    "types_runner.py",
])

py_library(
    name = "ruff_bin",
    srcs = ["ruff_bin.py"],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [requirement("ruff")],
)

py_binary(
    name = "ruff",
    srcs = ["ruff_main.py"],
    main = "ruff_main.py",
    deps = [":ruff_bin"],
)

ame_test(
    name = "ruff_bin_test",
    src = "ruff_bin_test.py",
    deps = [":ruff_bin"],
)

py_library(
    name = "types_runner_lib",
    srcs = ["types_runner.py"],
    imports = ["."],
)

ame_test(
    name = "types_runner_test",
    src = "types_runner_test.py",
    data = ["//:mypy.ini"],
    deps = [
        ":types_runner_lib",
        requirement("mypy"),
    ],
)

python_checks(
    name = "quality",
    srcs = glob(["*.py"]),
    deps = [":ruff_bin"],
)

starlark_checks(srcs = ["BUILD.bazel"] + glob(["*.bzl"]))
