load("@pip//:requirements.bzl", "requirement")
load("@rules_python//python:defs.bzl", "py_binary", "py_library")
load("//tools/bazel:defs.bzl", "starlark_checks")
load("//tools/python:defs.bzl", "ame_test", "python_checks")

exports_files([
    "check_runner.py",
    "pytest_runner.py",
])

py_library(
    name = "ruff_bin",
    srcs = ["ruff_bin.py"],
    imports = ["."],
    visibility = ["//visibility:public"],
    deps = [requirement("ruff")],
)

py_binary(
    name = "ruff",
    srcs = ["ruff_main.py"],
    main = "ruff_main.py",
    deps = [":ruff_bin"],
)

ame_test(
    name = "ruff_bin_test",
    src = "ruff_bin_test.py",
    deps = [":ruff_bin"],
)

python_checks(
    name = "quality",
    srcs = glob(["*.py"]),
)

starlark_checks(srcs = ["BUILD.bazel"] + glob(["*.bzl"]))
